# Auto-generated by the recorder (22.05.2026 09:49).
# Locator file: locators/e2e_test_flask.json

Feature: e2e_test_flask

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 09:49
    Given I open the recorded url "about:blank"
    Given I open the recorded url "https://example.com/"
    Given I open the recorded url "https://example.com/"
    When I click "cortexBigbannerClose"
    When I click "cortexBigbannerClose_2"

