# Auto-generated by the recorder (22.05.2026 09:59).
# Locator file: locators/recorded_20260522_095054.json

Feature: recorded_20260522_095054

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 09:59
    Given I open the recorded url "about:blank"
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "cortexBigbannerClose"
    When I click "cortexBigbannerClose_2"
    When I click "email"
    When I click "email_2"
    * I write "yasinbulgan1995" into "email_3"

