# Auto-generated by the recorder (22.05.2026 09:44).
# Locator file: locators/recorded_20260522_094146.json

Feature: recorded_20260522_094146

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 09:44
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "cortexBigbannerClose"
    When I click "email"
    When I click "email_2"
    When I click "password"
    When I click "password_2"
    When I click "email_3"
    When I click "email_4"
    * I write "yasin" into "email_5"
    When I click "password_3"
    When I click "password_4"
    * I enter encrypted password alias "recordedPassword" into "password_5"
    When I click "girisYapButton"
    When I click "girisYapButton_2"
    # [TEST] debug overlay button — 09:42:15
    # [TEST] debug overlay button — 09:42:16
    * I press "ESCAPE"

