# Auto-generated by the recorder (22.05.2026 10:19).
# Locator file: locators/recorded_20260522_101858.json

Feature: recorded_20260522_101858

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 10:19
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "cortexBigbannerClose"
    When I click "email"
    When I click "password"
    When I click "girisYapButton"
    * I write "jbjbjbjbj" into "email"
    * I enter encrypted password alias "recordedPassword" into "password"

