# Auto-generated by the recorder (22.05.2026 09:41).
# Locator file: locators/recorded_20260522_094008.json

Feature: recorded_20260522_094008

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 09:41
    Given I open the recorded url "about:blank"
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "cortexBigbannerClose"
    When I click "cortexBigbannerClose_2"
    When I click "email"
    When I click "email_2"
    When I click "password"
    When I click "password_2"
    When I click "girisYapButton"
    When I click "girisYapButton_2"
    When I click "email_3"
    When I click "email_4"
    When I click "email_5"
    When I click "email_6"
    Then I see "girisYapButton_3"
    Then I see "girisYapButton_4"

