# Auto-generated by the recorder (22.05.2026 10:02).
# Locator file: locators/recorded_20260522_100220.json

Feature: recorded_20260522_100220

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 10:02
    Given I open the recorded url "about:blank"
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"

