# Auto-generated by the recorder (22.05.2026 10:54).
# Locator file: locators/recorded_20260522_103537.json

Feature: recorded_20260522_103537

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 10:54
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "email"
    When I click "password"

