# Auto-generated by the recorder (21.05.2026 14:03).
# Locator file: locators/recorded_20260521_111327.json

Feature: recorded_20260521_111327

  @recorded @cortex
  Scenario: Recorded - 21.05.2026 14:03
    Given I open the recorded url "about:blank"

