# Auto-generated by the recorder (24.05.2026 22:47).
# Locator file: locators/recorded_20260524_224734.json

Feature: recorded_20260524_224734

  @recorded @cortex
  Scenario: Recorded - 24.05.2026 22:47
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "email"
    * I press "TAB"
    * I write "yasin" into "email"
    # [recorder] password persist FAILED for alias "recordedPassword": Failed to encrypt and save password
    # [recorder] To fix: set CORTEX_AES_KEY=<16 chars> in .env,
    # then run EncryptionManager.encryptAndSaveToPasswordFile(<plain>, "recordedPassword")
    * I enter encrypted password alias "recordedPassword" into "password"

