# Auto-generated by the recorder (22.05.2026 23:23).
# Locator file: locators/recorded_20260522_105501.json

Feature: recorded_20260522_105501

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 23:23
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    # [TEST] debug overlay button — 10:55:19
    # [TEST] debug overlay button — 10:55:19
    # [TEST] debug overlay button — 10:55:20
    When I click "element"
    When I click "email"
    When I click "elementLabel"
    When I click "girisYapButton"

