# Auto-generated by the recorder (22.05.2026 10:00).
# Locator file: locators/recorded_20260522_095940.json

Feature: recorded_20260522_095940

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 10:00
    Given I open the recorded url "about:blank"
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "cortexBigbannerClose"
    When I click "cortexBigbannerClose_2"
    When I click "email"
    When I click "email_2"
    When I click "password"
    When I click "password_2"
    When I click "email_3"
    When I click "email_4"
    When I click "password_3"
    When I click "password_4"
    * I write "sdsa" into "email_5"
    * I enter encrypted password alias "recordedPassword" into "password_5"
    When I click "girisYapButton"
    When I click "girisYapButton_2"
    * I write "sdsa@gmail.com" into "email_6"
    When I click "girisYapButton_3"
    When I click "girisYapButton_4"
    * I press "ENTER"

