# Auto-generated by the recorder (24.05.2026 16:33).
# Locator file: locators/recorded_20260524_163316.json

Feature: recorded_20260524_163316

  @recorded @cortex
  Scenario: Recorded - 24.05.2026 16:33
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    # [TEST] debug overlay button — 16:33:24
    When I click "email"
    When I click "password"
    When I click "girisYapButton"
    * I press "TAB"
    * I write "yasin" into "email"
    * I enter encrypted password alias "recordedPassword" into "password"
    When I click "girisYapButton"

