# Auto-generated by the recorder (22.05.2026 09:40).
# Locator file: locators/smoke_verify.json

Feature: smoke_verify

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 09:40
    Given I open the recorded url "about:blank"
    Given I open the recorded url "https://cortex-test.bgtsai.com/"
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    When I click "cortexBigbannerClose"
    When I click "cortexBigbannerClose_2"
    # [TEST] debug overlay button — 09:36:38
    # [TEST] debug overlay button — 09:36:38
    # [TEST] debug overlay button — 09:36:40
    # [TEST] debug overlay button — 09:36:41
    When I click "email"
    When I click "email_2"
    When I click "elementLabel"
    When I click "elementLabel_2"
    When I click "password"
    When I click "password_2"

