# Auto-generated by the recorder (21.05.2026 10:11).
# Locator file: locators/test145.json

Feature: test145

  @recorded @cortex
  Scenario: Recorded - 21.05.2026 10:11
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"

