# Auto-generated by the recorder (22.05.2026 10:37).
# Locator file: locators/yasin_retro_clean.json

Feature: yasin_retro_clean

  @recorded @cortex
  Scenario: Recorded - 22.05.2026 10:37
    Given I open the recorded url "https://cortex-test.bgtsai.com/login"
    * I write "yasinbulgan1995@gmail.com" into "email"

