/**
 * Framework Constants
 * Centralized configuration values and constants
 */

export const TIMEOUTS = {
  DEFAULT: 30000,
  ELEMENT_VISIBILITY: 5000,
  NETWORK_IDLE: 5000,
  OVERLAY_CLOSE: 2000,
  POLLING_INTERVAL: 100,
  MAX_POLLING_ATTEMPTS: 50,
  PAGE_LOAD: 30000,
  API_REQUEST: 10000
} as const;

export const LIMITS = {
  PRODUCT_LIMIT_MIN: 1,
  PRODUCT_LIMIT_MAX: 100,
  MAX_RETRY_ATTEMPTS: 3,
  DEFAULT_COIN_SELECTION_COUNT: 3,
  MAX_PARALLEL_WORKERS: 10
} as const;

export const CALCULATION_TOLERANCE = 0.01;

export const LOG_LEVELS = ['DEBUG', 'INFO', 'WARN', 'ERROR'] as const;
export type LogLevel = typeof LOG_LEVELS[number];

export const ENV_VARS = {
  ENVIRONMENT: 'ENVIRONMENT',
  HEADLESS: 'HEADLESS',
  LOG_LEVEL: 'LOG_LEVEL',
  PARIBU_BASE_URL: 'PARIBU_BASE_URL',
  QA_BASE_URL: 'QA_BASE_URL',
  STAGE_BASE_URL: 'STAGE_BASE_URL',
  PROD_BASE_URL: 'PROD_BASE_URL',
  BROWSER_LOCALE: 'BROWSER_LOCALE',
  BROWSER_TIMEZONE: 'BROWSER_TIMEZONE',
  DEFAULT_TIMEOUT: 'DEFAULT_TIMEOUT',
  API_BASE_URL: 'API_BASE_URL',
  API_TIMEOUT: 'API_TIMEOUT',
  SCREENSHOT_ON_FAILURE: 'SCREENSHOT_ON_FAILURE',
  VIDEO_ON_FAILURE: 'VIDEO_ON_FAILURE',
  TRACE_ON_FAILURE: 'TRACE_ON_FAILURE',
  PARALLEL_WORKERS: 'PARALLEL_WORKERS',
  MAX_RETRIES: 'MAX_RETRIES',
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  OPENAI_MODEL: 'OPENAI_MODEL',
  OPENAI_TEMPERATURE: 'OPENAI_TEMPERATURE',
  OPENAI_MAX_TOKENS: 'OPENAI_MAX_TOKENS'
} as const;

export const REQUIRED_ENV_VARS: string[] = [
  ENV_VARS.PARIBU_BASE_URL
];
