package recorder;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Writes the translator output to disk:
 *   {outputDir}/{featureName}.feature
 *   {outputDir}/locators/{featureName}.json
 *
 * Hooks.setUp loads the locator JSON by matching the feature filename, so
 * the recorded feature is immediately runnable.
 */
public class FeatureWriter {

    private final RecorderConfig cfg;
    private final Gson gson = new GsonBuilder().setPrettyPrinting().create();

    public FeatureWriter(RecorderConfig cfg) {
        this.cfg = cfg;
    }

    public Result write(ActionTranslator.TranslationResult tr) throws IOException {
        Path featureFile = cfg.outputDir.resolve(cfg.featureName + ".feature");
        Path locatorsDir = cfg.outputDir.resolve("locators");
        Path locatorFile = locatorsDir.resolve(cfg.featureName + ".json");

        Files.createDirectories(cfg.outputDir);
        Files.createDirectories(locatorsDir);

        String featureBody = renderFeature(tr.gherkinLines());
        Files.writeString(featureFile, featureBody);

        String locatorBody = renderLocators(tr.locatorEntries());
        Files.writeString(locatorFile, locatorBody);

        return new Result(featureFile, locatorFile, tr.gherkinLines().size(), tr.locatorEntries().size());
    }

    private String renderFeature(List<String> lines) {
        String ts = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm"));
        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by the recorder (").append(ts).append(").\n");
        sb.append("# Locator file: locators/").append(cfg.featureName).append(".json\n\n");
        sb.append("Feature: ").append(cfg.featureName).append("\n\n");
        sb.append("  @recorded @cortex\n");
        sb.append("  Scenario: Recorded - ").append(ts).append("\n");
        for (String line : lines) {
            sb.append(line).append("\n");
        }
        sb.append("\n");
        return sb.toString();
    }

    private String renderLocators(Map<String, Map<String, String>> entries) {
        return gson.toJson(entries.values());
    }

    public record Result(Path featureFile, Path locatorFile,
                         int actionCount, int locatorCount) {}
}
