"""
Nexus QA — Faz 5: Automation Code Generation Service
Onaylı test case'lerden → Gherkin feature file + Java NexusQA step defs + Playwright TS.

Üretim pipeline:
  1. approved TspmTestCase → Gherkin (.feature)
  2. Gherkin → Java step definitions (NexusQA framework)
  3. Gherkin → Playwright TypeScript test file
  4. Sonuçları TspmArtifact olarak DB'ye kaydet (veya sadece döndür)
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any, Optional

logger = logging.getLogger("nexusqa.automation_gen")

# ── Prompt helpers ────────────────────────────────────────────────────────────

def _build_gherkin_prompt(test_cases: list[dict[str, Any]], feature_name: str) -> str:
    """Build user message to generate Gherkin from test cases."""
    tc_summary = []
    for i, tc in enumerate(test_cases[:15], 1):  # max 15 TCs per feature
        steps_text = ""
        if tc.get("preconditions"):
            steps_text += "  Ön koşullar: " + "; ".join(tc["preconditions"]) + "\n"
        if tc.get("steps"):
            for s in tc["steps"]:
                steps_text += f"  {s.get('order','')}: {s.get('action','')} → {s.get('expected','')}\n"
        if tc.get("expected_result"):
            steps_text += f"  Beklenen Sonuç: {tc['expected_result']}\n"

        tc_summary.append(
            f"{i}. [{tc.get('test_type','functional').upper()}] {tc['title']}\n"
            f"   Öncelik: {tc.get('priority','medium')} | Risk: {tc.get('risk_level','medium')}\n"
            f"{steps_text}"
        )

    tc_text = "\n".join(tc_summary)
    return f"""Feature dosyası oluştur. Feature adı: "{feature_name}"

Test Case'ler:
{tc_text}

Kurallar:
- Türkçe Cucumber formatı kullan: "Olduğu gibi" / "Eğer" / "Ve" / "O zaman"
- Her test case için ayrı Scenario yaz
- Scenario başlığı test case başlığından alınsın
- @etiket olarak priority ve test_type ekle
- Parameterized testler için Scenario Outline kullan
- Feature başına "# ai-generated by Nexus QA" yorumu ekle

Yanıt SADECE .feature dosyası içeriği olmalı, başka açıklama ekleme."""


def _build_java_steps_prompt(gherkin_content: str, feature_name: str) -> str:
    """Build user message to generate Java NexusQA step definitions."""
    return f"""Aşağıdaki Gherkin senaryoları için Java NexusQA (Selenium 4 + Cucumber) step definition sınıfı üret.

Feature: {feature_name}

Gherkin İçeriği:
{gherkin_content[:3000]}

Kurallar:
- Paket: com.nexusqa.steps
- Sınıf adı: {_to_java_class_name(feature_name)}Steps
- Selenium 4 WebDriver kullan
- @Given / @When / @Then / @And Cucumber annotation'larını kullan
- Her step için Türkçe pattern kullan
- WebDriver'ı @Before setUp ile başlat, @After tearDown ile kapat
- Önce mevcut NexusQA step'lerini kontrol et — yeniden kullan
- Sadece Java kodu yaz, açıklama ekleme"""


def _build_playwright_prompt(test_cases: list[dict[str, Any]], feature_name: str) -> str:
    """Build user message to generate Playwright TypeScript test file."""
    tc_summary = "\n".join(
        f"- {tc['title']} [{tc.get('test_type','functional')}] priority:{tc.get('priority','medium')}"
        for tc in test_cases[:15]
    )
    return f"""Aşağıdaki test case'leri için Playwright TypeScript test dosyası üret.

Feature: {feature_name}
Test Cases:
{tc_summary}

Kurallar:
- @playwright/test import et
- test.describe() ile grupla
- Her test case için ayrı test() bloğu yaz
- page fixture kullan
- Türkçe test açıklamaları yaz
- locator stratejileri: getByRole, getByLabel, getByTestId tercih et
- expect() assertions ekle
- beforeEach/afterEach ile setup/teardown
- Dosya başına "// ai-generated by Nexus QA" yorumu ekle

Yanıt SADECE TypeScript kodu olmalı."""


_TR_CHAR_MAP = str.maketrans(
    "ğüşıöçĞÜŞİÖÇ",
    "gusiocGUSIOC",
)


def _to_java_class_name(name: str) -> str:
    """Feature adını geçerli Java sınıf adına dönüştür (Türkçe karakter güvenli)."""
    # 1. Türkçe karakterleri ASCII karşılıklarıyla değiştir
    ascii_name = name.translate(_TR_CHAR_MAP)
    # 2. Geçersiz Java karakterlerini boşlukla değiştir
    words = re.sub(r"[^a-zA-Z0-9\s]", " ", ascii_name).split()
    # 3. Her kelimeyi büyük harfle başlat
    return "".join(w.capitalize() for w in words if w) or "Feature"


def _strip_code_fences(text: str, expected_lang: str = "") -> str:
    """Strip markdown code fences."""
    # Remove ```language\n...\n```
    patterns = [
        rf"^```{expected_lang}\s*\n(.*?)\n```\s*$",
        r"^```\w*\s*\n(.*?)\n```\s*$",
        r"^```\s*\n(.*?)\n```\s*$",
    ]
    for pat in patterns:
        m = re.match(pat, text.strip(), re.DOTALL)
        if m:
            return m.group(1)
    return text.strip()


# ── Core Generation Functions ─────────────────────────────────────────────────

def generate_gherkin_from_test_cases(
    test_cases: list[dict[str, Any]],
    feature_name: str,
    project_id: Optional[str] = None,
) -> dict[str, Any]:
    """
    Approved test case'lerden Gherkin feature file üret.
    Returns: {gherkin: str, feature_name: str, scenario_count: int, ai_provider: str}
    """
    from app.domains.ai.gateway_client import gateway_complete

    prompt = _build_gherkin_prompt(test_cases, feature_name)
    raw = gateway_complete(
        task_type="generate_gherkin",
        user_message=prompt,
        temperature=0.3,
        max_tokens=4000,
        project_id=project_id,
    )

    gherkin = _strip_code_fences(raw, "gherkin")
    scenario_count = len(re.findall(r"^\s*Scenario", gherkin, re.MULTILINE))

    return {
        "gherkin": gherkin,
        "feature_name": feature_name,
        "scenario_count": scenario_count,
        "filename": f"{_to_java_class_name(feature_name).lower()}.feature",
    }


def generate_java_steps_from_gherkin(
    gherkin_content: str,
    feature_name: str,
    project_id: Optional[str] = None,
) -> dict[str, Any]:
    """
    Gherkin'den Java NexusQA step definitions üret.
    Returns: {java_code: str, class_name: str, method_count: int}
    """
    from app.domains.ai.gateway_client import gateway_complete

    prompt = _build_java_steps_prompt(gherkin_content, feature_name)
    raw = gateway_complete(
        task_type="generate_java_steps",
        user_message=prompt,
        temperature=0.2,
        max_tokens=4000,
        project_id=project_id,
    )

    java_code = _strip_code_fences(raw, "java")
    class_name = _to_java_class_name(feature_name) + "Steps"
    method_count = len(re.findall(r"@(?:Given|When|Then|And)\s*\(", java_code))

    return {
        "java_code": java_code,
        "class_name": class_name,
        "filename": f"{class_name}.java",
        "method_count": method_count,
    }


def generate_playwright_from_test_cases(
    test_cases: list[dict[str, Any]],
    feature_name: str,
    project_id: Optional[str] = None,
) -> dict[str, Any]:
    """
    Test case'lerden Playwright TypeScript test dosyası üret.
    Returns: {ts_code: str, test_count: int, filename: str}
    """
    from app.domains.ai.gateway_client import gateway_complete

    prompt = _build_playwright_prompt(test_cases, feature_name)
    raw = gateway_complete(
        task_type="generate_playwright",
        user_message=prompt,
        temperature=0.3,
        max_tokens=4000,
        project_id=project_id,
    )

    ts_code = _strip_code_fences(raw, "typescript")
    test_count = len(re.findall(r"\btest\s*\(", ts_code))
    class_name = _to_java_class_name(feature_name)

    return {
        "ts_code": ts_code,
        "filename": f"{class_name.lower()}.spec.ts",
        "test_count": test_count,
    }


# ── Full Pipeline ─────────────────────────────────────────────────────────────

def generate_full_automation_package(
    test_cases: list[dict[str, Any]],
    feature_name: str,
    include_java: bool = True,
    include_playwright: bool = True,
    project_id: Optional[str] = None,
) -> dict[str, Any]:
    """
    Tam otomasyon paketi: Gherkin + Java + Playwright.
    """
    result: dict[str, Any] = {
        "feature_name": feature_name,
        "test_case_count": len(test_cases),
        "gherkin": None,
        "java": None,
        "playwright": None,
        "errors": [],
    }

    # 1. Gherkin (always)
    try:
        gherkin_result = generate_gherkin_from_test_cases(test_cases, feature_name, project_id)
        result["gherkin"] = gherkin_result
    except Exception as e:
        logger.error(f"Gherkin üretimi başarısız: {e}")
        result["errors"].append(f"Gherkin: {e}")
        return result  # Can't continue without gherkin

    gherkin_content = gherkin_result["gherkin"]

    # 2. Java steps (from gherkin)
    if include_java:
        try:
            result["java"] = generate_java_steps_from_gherkin(gherkin_content, feature_name, project_id)
        except Exception as e:
            logger.error(f"Java step üretimi başarısız: {e}")
            result["errors"].append(f"Java: {e}")

    # 3. Playwright TS (from test cases)
    if include_playwright:
        try:
            result["playwright"] = generate_playwright_from_test_cases(test_cases, feature_name, project_id)
        except Exception as e:
            logger.error(f"Playwright üretimi başarısız: {e}")
            result["errors"].append(f"Playwright: {e}")

    return result
